name: pp_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - docopt
  - cmake >= 3.12
  - pybind11
  - zlib
  # osx
  - llvm-openmp  # [osx]
  - gfortran_impl_osx-64  # [osx]
  # linux
  #- libgomp      # [linux64]
  #- libgfortran-ng        # [linux64]